# Generated by Django 3.2.2 on 2021-05-30 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
