# Generated by Django 3.2.2 on 2021-05-28 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomenclature', models.CharField(max_length=250)),
                ('certificate_number', models.TextField(max_length=250)),
                ('calibrated_date', models.DateField()),
                ('certificate_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('company', models.ForeignKey(db_column='company_name', on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('user', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
