# Generated by Django 3.2.2 on 2021-05-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
